name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-generator:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check out Git repository
        uses: actions/checkout@v3 
        with: 
          path: openapi-forge-rust
       
      - name: Install Node.js dependencies for forge-rust
        run: |
          cd openapi-forge-rust
          npm install

      - name: Check out the openapi-forge generator
        uses: actions/checkout@v3
        with: 
          repository: ScottLogic/openapi-forge
          path: openapi-forge

      - name: Install Node.js dependencies for forge
        run: |
          cd openapi-forge
          npm install

      - name: Run the tests
        run: |
          cd openapi-forge-rust
          npm test